/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminProvidersRouteImport } from './routes/_admin/providers'
import { Route as AdminHealthRouteImport } from './routes/_admin/health'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminAuditRouteImport } from './routes/_admin/audit'
import { Route as AdminOrganisationsIndexRouteImport } from './routes/_admin/organisations/index'
import { Route as AdminMarketplaceIndexRouteImport } from './routes/_admin/marketplace/index'
import { Route as AdminOrganisationsOrgIdRouteImport } from './routes/_admin/organisations/$orgId'
import { Route as AdminMarketplaceTemplatesRouteImport } from './routes/_admin/marketplace/templates'
import { Route as AdminMarketplaceAgentsRouteImport } from './routes/_admin/marketplace/agents'
import { Route as AdminMarketplaceTemplatesIndexRouteImport } from './routes/_admin/marketplace/templates.index'
import { Route as AdminMarketplaceAgentsIndexRouteImport } from './routes/_admin/marketplace/agents.index'
import { Route as AdminMarketplaceTemplatesNewRouteImport } from './routes/_admin/marketplace/templates.new'
import { Route as AdminMarketplaceTemplatesTemplateIdRouteImport } from './routes/_admin/marketplace/templates.$templateId'
import { Route as AdminMarketplaceAgentsNewRouteImport } from './routes/_admin/marketplace/agents.new'
import { Route as AdminMarketplaceAgentsAgentIdRouteImport } from './routes/_admin/marketplace/agents.$agentId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganisationsIndexRoute = AdminOrganisationsIndexRouteImport.update({
  id: '/organisations/',
  path: '/organisations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketplaceIndexRoute = AdminMarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganisationsOrgIdRoute = AdminOrganisationsOrgIdRouteImport.update({
  id: '/organisations/$orgId',
  path: '/organisations/$orgId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketplaceTemplatesRoute =
  AdminMarketplaceTemplatesRouteImport.update({
    id: '/marketplace/templates',
    path: '/marketplace/templates',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMarketplaceAgentsRoute = AdminMarketplaceAgentsRouteImport.update({
  id: '/marketplace/agents',
  path: '/marketplace/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketplaceTemplatesIndexRoute =
  AdminMarketplaceTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminMarketplaceTemplatesRoute,
  } as any)
const AdminMarketplaceAgentsIndexRoute =
  AdminMarketplaceAgentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminMarketplaceAgentsRoute,
  } as any)
const AdminMarketplaceTemplatesNewRoute =
  AdminMarketplaceTemplatesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminMarketplaceTemplatesRoute,
  } as any)
const AdminMarketplaceTemplatesTemplateIdRoute =
  AdminMarketplaceTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => AdminMarketplaceTemplatesRoute,
  } as any)
const AdminMarketplaceAgentsNewRoute =
  AdminMarketplaceAgentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminMarketplaceAgentsRoute,
  } as any)
const AdminMarketplaceAgentsAgentIdRoute =
  AdminMarketplaceAgentsAgentIdRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => AdminMarketplaceAgentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AdminAuditRoute
  '/dashboard': typeof AdminDashboardRoute
  '/health': typeof AdminHealthRoute
  '/providers': typeof AdminProvidersRoute
  '/settings': typeof AdminSettingsRoute
  '/users': typeof AdminUsersRoute
  '/marketplace/agents': typeof AdminMarketplaceAgentsRouteWithChildren
  '/marketplace/templates': typeof AdminMarketplaceTemplatesRouteWithChildren
  '/organisations/$orgId': typeof AdminOrganisationsOrgIdRoute
  '/marketplace/': typeof AdminMarketplaceIndexRoute
  '/organisations/': typeof AdminOrganisationsIndexRoute
  '/marketplace/agents/$agentId': typeof AdminMarketplaceAgentsAgentIdRoute
  '/marketplace/agents/new': typeof AdminMarketplaceAgentsNewRoute
  '/marketplace/templates/$templateId': typeof AdminMarketplaceTemplatesTemplateIdRoute
  '/marketplace/templates/new': typeof AdminMarketplaceTemplatesNewRoute
  '/marketplace/agents/': typeof AdminMarketplaceAgentsIndexRoute
  '/marketplace/templates/': typeof AdminMarketplaceTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AdminAuditRoute
  '/dashboard': typeof AdminDashboardRoute
  '/health': typeof AdminHealthRoute
  '/providers': typeof AdminProvidersRoute
  '/settings': typeof AdminSettingsRoute
  '/users': typeof AdminUsersRoute
  '/organisations/$orgId': typeof AdminOrganisationsOrgIdRoute
  '/marketplace': typeof AdminMarketplaceIndexRoute
  '/organisations': typeof AdminOrganisationsIndexRoute
  '/marketplace/agents/$agentId': typeof AdminMarketplaceAgentsAgentIdRoute
  '/marketplace/agents/new': typeof AdminMarketplaceAgentsNewRoute
  '/marketplace/templates/$templateId': typeof AdminMarketplaceTemplatesTemplateIdRoute
  '/marketplace/templates/new': typeof AdminMarketplaceTemplatesNewRoute
  '/marketplace/agents': typeof AdminMarketplaceAgentsIndexRoute
  '/marketplace/templates': typeof AdminMarketplaceTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/audit': typeof AdminAuditRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/health': typeof AdminHealthRoute
  '/_admin/providers': typeof AdminProvidersRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/marketplace/agents': typeof AdminMarketplaceAgentsRouteWithChildren
  '/_admin/marketplace/templates': typeof AdminMarketplaceTemplatesRouteWithChildren
  '/_admin/organisations/$orgId': typeof AdminOrganisationsOrgIdRoute
  '/_admin/marketplace/': typeof AdminMarketplaceIndexRoute
  '/_admin/organisations/': typeof AdminOrganisationsIndexRoute
  '/_admin/marketplace/agents/$agentId': typeof AdminMarketplaceAgentsAgentIdRoute
  '/_admin/marketplace/agents/new': typeof AdminMarketplaceAgentsNewRoute
  '/_admin/marketplace/templates/$templateId': typeof AdminMarketplaceTemplatesTemplateIdRoute
  '/_admin/marketplace/templates/new': typeof AdminMarketplaceTemplatesNewRoute
  '/_admin/marketplace/agents/': typeof AdminMarketplaceAgentsIndexRoute
  '/_admin/marketplace/templates/': typeof AdminMarketplaceTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/dashboard'
    | '/health'
    | '/providers'
    | '/settings'
    | '/users'
    | '/marketplace/agents'
    | '/marketplace/templates'
    | '/organisations/$orgId'
    | '/marketplace/'
    | '/organisations/'
    | '/marketplace/agents/$agentId'
    | '/marketplace/agents/new'
    | '/marketplace/templates/$templateId'
    | '/marketplace/templates/new'
    | '/marketplace/agents/'
    | '/marketplace/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit'
    | '/dashboard'
    | '/health'
    | '/providers'
    | '/settings'
    | '/users'
    | '/organisations/$orgId'
    | '/marketplace'
    | '/organisations'
    | '/marketplace/agents/$agentId'
    | '/marketplace/agents/new'
    | '/marketplace/templates/$templateId'
    | '/marketplace/templates/new'
    | '/marketplace/agents'
    | '/marketplace/templates'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/audit'
    | '/_admin/dashboard'
    | '/_admin/health'
    | '/_admin/providers'
    | '/_admin/settings'
    | '/_admin/users'
    | '/_admin/marketplace/agents'
    | '/_admin/marketplace/templates'
    | '/_admin/organisations/$orgId'
    | '/_admin/marketplace/'
    | '/_admin/organisations/'
    | '/_admin/marketplace/agents/$agentId'
    | '/_admin/marketplace/agents/new'
    | '/_admin/marketplace/templates/$templateId'
    | '/_admin/marketplace/templates/new'
    | '/_admin/marketplace/agents/'
    | '/_admin/marketplace/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/providers': {
      id: '/_admin/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/health': {
      id: '/_admin/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/audit': {
      id: '/_admin/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisations/': {
      id: '/_admin/organisations/'
      path: '/organisations'
      fullPath: '/organisations/'
      preLoaderRoute: typeof AdminOrganisationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/marketplace/': {
      id: '/_admin/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof AdminMarketplaceIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisations/$orgId': {
      id: '/_admin/organisations/$orgId'
      path: '/organisations/$orgId'
      fullPath: '/organisations/$orgId'
      preLoaderRoute: typeof AdminOrganisationsOrgIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/marketplace/templates': {
      id: '/_admin/marketplace/templates'
      path: '/marketplace/templates'
      fullPath: '/marketplace/templates'
      preLoaderRoute: typeof AdminMarketplaceTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/marketplace/agents': {
      id: '/_admin/marketplace/agents'
      path: '/marketplace/agents'
      fullPath: '/marketplace/agents'
      preLoaderRoute: typeof AdminMarketplaceAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/marketplace/templates/': {
      id: '/_admin/marketplace/templates/'
      path: '/'
      fullPath: '/marketplace/templates/'
      preLoaderRoute: typeof AdminMarketplaceTemplatesIndexRouteImport
      parentRoute: typeof AdminMarketplaceTemplatesRoute
    }
    '/_admin/marketplace/agents/': {
      id: '/_admin/marketplace/agents/'
      path: '/'
      fullPath: '/marketplace/agents/'
      preLoaderRoute: typeof AdminMarketplaceAgentsIndexRouteImport
      parentRoute: typeof AdminMarketplaceAgentsRoute
    }
    '/_admin/marketplace/templates/new': {
      id: '/_admin/marketplace/templates/new'
      path: '/new'
      fullPath: '/marketplace/templates/new'
      preLoaderRoute: typeof AdminMarketplaceTemplatesNewRouteImport
      parentRoute: typeof AdminMarketplaceTemplatesRoute
    }
    '/_admin/marketplace/templates/$templateId': {
      id: '/_admin/marketplace/templates/$templateId'
      path: '/$templateId'
      fullPath: '/marketplace/templates/$templateId'
      preLoaderRoute: typeof AdminMarketplaceTemplatesTemplateIdRouteImport
      parentRoute: typeof AdminMarketplaceTemplatesRoute
    }
    '/_admin/marketplace/agents/new': {
      id: '/_admin/marketplace/agents/new'
      path: '/new'
      fullPath: '/marketplace/agents/new'
      preLoaderRoute: typeof AdminMarketplaceAgentsNewRouteImport
      parentRoute: typeof AdminMarketplaceAgentsRoute
    }
    '/_admin/marketplace/agents/$agentId': {
      id: '/_admin/marketplace/agents/$agentId'
      path: '/$agentId'
      fullPath: '/marketplace/agents/$agentId'
      preLoaderRoute: typeof AdminMarketplaceAgentsAgentIdRouteImport
      parentRoute: typeof AdminMarketplaceAgentsRoute
    }
  }
}

interface AdminMarketplaceAgentsRouteChildren {
  AdminMarketplaceAgentsAgentIdRoute: typeof AdminMarketplaceAgentsAgentIdRoute
  AdminMarketplaceAgentsNewRoute: typeof AdminMarketplaceAgentsNewRoute
  AdminMarketplaceAgentsIndexRoute: typeof AdminMarketplaceAgentsIndexRoute
}

const AdminMarketplaceAgentsRouteChildren: AdminMarketplaceAgentsRouteChildren =
  {
    AdminMarketplaceAgentsAgentIdRoute: AdminMarketplaceAgentsAgentIdRoute,
    AdminMarketplaceAgentsNewRoute: AdminMarketplaceAgentsNewRoute,
    AdminMarketplaceAgentsIndexRoute: AdminMarketplaceAgentsIndexRoute,
  }

const AdminMarketplaceAgentsRouteWithChildren =
  AdminMarketplaceAgentsRoute._addFileChildren(
    AdminMarketplaceAgentsRouteChildren,
  )

interface AdminMarketplaceTemplatesRouteChildren {
  AdminMarketplaceTemplatesTemplateIdRoute: typeof AdminMarketplaceTemplatesTemplateIdRoute
  AdminMarketplaceTemplatesNewRoute: typeof AdminMarketplaceTemplatesNewRoute
  AdminMarketplaceTemplatesIndexRoute: typeof AdminMarketplaceTemplatesIndexRoute
}

const AdminMarketplaceTemplatesRouteChildren: AdminMarketplaceTemplatesRouteChildren =
  {
    AdminMarketplaceTemplatesTemplateIdRoute:
      AdminMarketplaceTemplatesTemplateIdRoute,
    AdminMarketplaceTemplatesNewRoute: AdminMarketplaceTemplatesNewRoute,
    AdminMarketplaceTemplatesIndexRoute: AdminMarketplaceTemplatesIndexRoute,
  }

const AdminMarketplaceTemplatesRouteWithChildren =
  AdminMarketplaceTemplatesRoute._addFileChildren(
    AdminMarketplaceTemplatesRouteChildren,
  )

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminMarketplaceAgentsRoute: typeof AdminMarketplaceAgentsRouteWithChildren
  AdminMarketplaceTemplatesRoute: typeof AdminMarketplaceTemplatesRouteWithChildren
  AdminOrganisationsOrgIdRoute: typeof AdminOrganisationsOrgIdRoute
  AdminMarketplaceIndexRoute: typeof AdminMarketplaceIndexRoute
  AdminOrganisationsIndexRoute: typeof AdminOrganisationsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminMarketplaceAgentsRoute: AdminMarketplaceAgentsRouteWithChildren,
  AdminMarketplaceTemplatesRoute: AdminMarketplaceTemplatesRouteWithChildren,
  AdminOrganisationsOrgIdRoute: AdminOrganisationsOrgIdRoute,
  AdminMarketplaceIndexRoute: AdminMarketplaceIndexRoute,
  AdminOrganisationsIndexRoute: AdminOrganisationsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
