/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as AuthUsageRouteImport } from './routes/_auth/usage'
import { Route as AuthToolsRouteImport } from './routes/_auth/tools'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthSearchRouteImport } from './routes/_auth/search'
import { Route as AuthSandboxRouteImport } from './routes/_auth/sandbox'
import { Route as AuthResearchRouteImport } from './routes/_auth/research'
import { Route as AuthPromptsRouteImport } from './routes/_auth/prompts'
import { Route as AuthPlaygroundRouteImport } from './routes/_auth/playground'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthModelCompareRouteImport } from './routes/_auth/model-compare'
import { Route as AuthMcpRouteImport } from './routes/_auth/mcp'
import { Route as AuthKnowledgeRouteImport } from './routes/_auth/knowledge'
import { Route as AuthHelpRouteImport } from './routes/_auth/help'
import { Route as AuthFoldersRouteImport } from './routes/_auth/folders'
import { Route as AuthFilesRouteImport } from './routes/_auth/files'
import { Route as AuthExploreRouteImport } from './routes/_auth/explore'
import { Route as AuthDevWidgetsRouteImport } from './routes/_auth/dev-widgets'
import { Route as AuthAgentsRouteImport } from './routes/_auth/agents'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings.index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin.index'
import { Route as AuthSettingsShortcutsRouteImport } from './routes/_auth/settings.shortcuts'
import { Route as AuthSettingsSecurityRouteImport } from './routes/_auth/settings.security'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth/settings.profile'
import { Route as AuthSettingsNotificationsRouteImport } from './routes/_auth/settings.notifications'
import { Route as AuthSettingsImportExportRouteImport } from './routes/_auth/settings.import-export'
import { Route as AuthSettingsAppearanceRouteImport } from './routes/_auth/settings.appearance'
import { Route as AuthSettingsApiKeysRouteImport } from './routes/_auth/settings.api-keys'
import { Route as AuthKnowledgeNewRouteImport } from './routes/_auth/knowledge.new'
import { Route as AuthKnowledgeIdRouteImport } from './routes/_auth/knowledge.$id'
import { Route as AuthConversationsNewRouteImport } from './routes/_auth/conversations.new'
import { Route as AuthConversationsIdRouteImport } from './routes/_auth/conversations.$id'
import { Route as AuthAgentsNewRouteImport } from './routes/_auth/agents.new'
import { Route as AuthAgentsMarketplaceRouteImport } from './routes/_auth/agents.marketplace'
import { Route as AuthAgentsIdRouteImport } from './routes/_auth/agents.$id'
import { Route as AuthAdminSsoRouteImport } from './routes/_auth/admin.sso'
import { Route as AuthAdminSecurityRouteImport } from './routes/_auth/admin.security'
import { Route as AuthAdminRateLimitsRouteImport } from './routes/_auth/admin.rate-limits'
import { Route as AuthAdminOrgSettingsRouteImport } from './routes/_auth/admin.org-settings'
import { Route as AuthAdminModelsRouteImport } from './routes/_auth/admin.models'
import { Route as AuthAdminMembersRouteImport } from './routes/_auth/admin.members'
import { Route as AuthAdminIntegrationsRouteImport } from './routes/_auth/admin.integrations'
import { Route as AuthAdminHealthRouteImport } from './routes/_auth/admin.health'
import { Route as AuthAdminGroupsRouteImport } from './routes/_auth/admin.groups'
import { Route as AuthAdminEvalsRouteImport } from './routes/_auth/admin.evals'
import { Route as AuthAdminDomainsRouteImport } from './routes/_auth/admin.domains'
import { Route as AuthAdminDataRetentionRouteImport } from './routes/_auth/admin.data-retention'
import { Route as AuthAdminContentFilterRouteImport } from './routes/_auth/admin.content-filter'
import { Route as AuthAdminBrandingRouteImport } from './routes/_auth/admin.branding'
import { Route as AuthAdminBillingRouteImport } from './routes/_auth/admin.billing'
import { Route as AuthAdminAuditRouteImport } from './routes/_auth/admin.audit'
import { Route as AuthAdminAnalyticsRouteImport } from './routes/_auth/admin.analytics'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUsageRoute = AuthUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthRoute,
} as any)
const AuthToolsRoute = AuthToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSearchRoute = AuthSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSandboxRoute = AuthSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResearchRoute = AuthResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPromptsRoute = AuthPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPlaygroundRoute = AuthPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthModelCompareRoute = AuthModelCompareRouteImport.update({
  id: '/model-compare',
  path: '/model-compare',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMcpRoute = AuthMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthKnowledgeRoute = AuthKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHelpRoute = AuthHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFoldersRoute = AuthFoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFilesRoute = AuthFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthRoute,
} as any)
const AuthExploreRoute = AuthExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDevWidgetsRoute = AuthDevWidgetsRouteImport.update({
  id: '/dev-widgets',
  path: '/dev-widgets',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsRoute = AuthAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthSettingsShortcutsRoute = AuthSettingsShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsSecurityRoute = AuthSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsNotificationsRoute =
  AuthSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthSettingsImportExportRoute =
  AuthSettingsImportExportRouteImport.update({
    id: '/import-export',
    path: '/import-export',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthSettingsAppearanceRoute = AuthSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsApiKeysRoute = AuthSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthKnowledgeNewRoute = AuthKnowledgeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthKnowledgeRoute,
} as any)
const AuthKnowledgeIdRoute = AuthKnowledgeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthKnowledgeRoute,
} as any)
const AuthConversationsNewRoute = AuthConversationsNewRouteImport.update({
  id: '/conversations/new',
  path: '/conversations/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConversationsIdRoute = AuthConversationsIdRouteImport.update({
  id: '/conversations/$id',
  path: '/conversations/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsNewRoute = AuthAgentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthAgentsRoute,
} as any)
const AuthAgentsMarketplaceRoute = AuthAgentsMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AuthAgentsRoute,
} as any)
const AuthAgentsIdRoute = AuthAgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthAgentsRoute,
} as any)
const AuthAdminSsoRoute = AuthAdminSsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminSecurityRoute = AuthAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminRateLimitsRoute = AuthAdminRateLimitsRouteImport.update({
  id: '/rate-limits',
  path: '/rate-limits',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminOrgSettingsRoute = AuthAdminOrgSettingsRouteImport.update({
  id: '/org-settings',
  path: '/org-settings',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminModelsRoute = AuthAdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminMembersRoute = AuthAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminIntegrationsRoute = AuthAdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminHealthRoute = AuthAdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminGroupsRoute = AuthAdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminEvalsRoute = AuthAdminEvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminDomainsRoute = AuthAdminDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminDataRetentionRoute = AuthAdminDataRetentionRouteImport.update({
  id: '/data-retention',
  path: '/data-retention',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminContentFilterRoute = AuthAdminContentFilterRouteImport.update({
  id: '/content-filter',
  path: '/content-filter',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminBrandingRoute = AuthAdminBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminBillingRoute = AuthAdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminAuditRoute = AuthAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminAnalyticsRoute = AuthAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/agents': typeof AuthAgentsRouteWithChildren
  '/dev-widgets': typeof AuthDevWidgetsRoute
  '/explore': typeof AuthExploreRoute
  '/files': typeof AuthFilesRoute
  '/folders': typeof AuthFoldersRoute
  '/help': typeof AuthHelpRoute
  '/knowledge': typeof AuthKnowledgeRouteWithChildren
  '/mcp': typeof AuthMcpRoute
  '/model-compare': typeof AuthModelCompareRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/playground': typeof AuthPlaygroundRoute
  '/prompts': typeof AuthPromptsRoute
  '/research': typeof AuthResearchRoute
  '/sandbox': typeof AuthSandboxRoute
  '/search': typeof AuthSearchRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/tools': typeof AuthToolsRoute
  '/usage': typeof AuthUsageRoute
  '/shared/$token': typeof SharedTokenRoute
  '/admin/analytics': typeof AuthAdminAnalyticsRoute
  '/admin/audit': typeof AuthAdminAuditRoute
  '/admin/billing': typeof AuthAdminBillingRoute
  '/admin/branding': typeof AuthAdminBrandingRoute
  '/admin/content-filter': typeof AuthAdminContentFilterRoute
  '/admin/data-retention': typeof AuthAdminDataRetentionRoute
  '/admin/domains': typeof AuthAdminDomainsRoute
  '/admin/evals': typeof AuthAdminEvalsRoute
  '/admin/groups': typeof AuthAdminGroupsRoute
  '/admin/health': typeof AuthAdminHealthRoute
  '/admin/integrations': typeof AuthAdminIntegrationsRoute
  '/admin/members': typeof AuthAdminMembersRoute
  '/admin/models': typeof AuthAdminModelsRoute
  '/admin/org-settings': typeof AuthAdminOrgSettingsRoute
  '/admin/rate-limits': typeof AuthAdminRateLimitsRoute
  '/admin/security': typeof AuthAdminSecurityRoute
  '/admin/sso': typeof AuthAdminSsoRoute
  '/agents/$id': typeof AuthAgentsIdRoute
  '/agents/marketplace': typeof AuthAgentsMarketplaceRoute
  '/agents/new': typeof AuthAgentsNewRoute
  '/conversations/$id': typeof AuthConversationsIdRoute
  '/conversations/new': typeof AuthConversationsNewRoute
  '/knowledge/$id': typeof AuthKnowledgeIdRoute
  '/knowledge/new': typeof AuthKnowledgeNewRoute
  '/settings/api-keys': typeof AuthSettingsApiKeysRoute
  '/settings/appearance': typeof AuthSettingsAppearanceRoute
  '/settings/import-export': typeof AuthSettingsImportExportRoute
  '/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/settings/shortcuts': typeof AuthSettingsShortcutsRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/agents': typeof AuthAgentsRouteWithChildren
  '/dev-widgets': typeof AuthDevWidgetsRoute
  '/explore': typeof AuthExploreRoute
  '/files': typeof AuthFilesRoute
  '/folders': typeof AuthFoldersRoute
  '/help': typeof AuthHelpRoute
  '/knowledge': typeof AuthKnowledgeRouteWithChildren
  '/mcp': typeof AuthMcpRoute
  '/model-compare': typeof AuthModelCompareRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/playground': typeof AuthPlaygroundRoute
  '/prompts': typeof AuthPromptsRoute
  '/research': typeof AuthResearchRoute
  '/sandbox': typeof AuthSandboxRoute
  '/search': typeof AuthSearchRoute
  '/tools': typeof AuthToolsRoute
  '/usage': typeof AuthUsageRoute
  '/shared/$token': typeof SharedTokenRoute
  '/': typeof AuthIndexRoute
  '/admin/analytics': typeof AuthAdminAnalyticsRoute
  '/admin/audit': typeof AuthAdminAuditRoute
  '/admin/billing': typeof AuthAdminBillingRoute
  '/admin/branding': typeof AuthAdminBrandingRoute
  '/admin/content-filter': typeof AuthAdminContentFilterRoute
  '/admin/data-retention': typeof AuthAdminDataRetentionRoute
  '/admin/domains': typeof AuthAdminDomainsRoute
  '/admin/evals': typeof AuthAdminEvalsRoute
  '/admin/groups': typeof AuthAdminGroupsRoute
  '/admin/health': typeof AuthAdminHealthRoute
  '/admin/integrations': typeof AuthAdminIntegrationsRoute
  '/admin/members': typeof AuthAdminMembersRoute
  '/admin/models': typeof AuthAdminModelsRoute
  '/admin/org-settings': typeof AuthAdminOrgSettingsRoute
  '/admin/rate-limits': typeof AuthAdminRateLimitsRoute
  '/admin/security': typeof AuthAdminSecurityRoute
  '/admin/sso': typeof AuthAdminSsoRoute
  '/agents/$id': typeof AuthAgentsIdRoute
  '/agents/marketplace': typeof AuthAgentsMarketplaceRoute
  '/agents/new': typeof AuthAgentsNewRoute
  '/conversations/$id': typeof AuthConversationsIdRoute
  '/conversations/new': typeof AuthConversationsNewRoute
  '/knowledge/$id': typeof AuthKnowledgeIdRoute
  '/knowledge/new': typeof AuthKnowledgeNewRoute
  '/settings/api-keys': typeof AuthSettingsApiKeysRoute
  '/settings/appearance': typeof AuthSettingsAppearanceRoute
  '/settings/import-export': typeof AuthSettingsImportExportRoute
  '/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/settings/shortcuts': typeof AuthSettingsShortcutsRoute
  '/admin': typeof AuthAdminIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/agents': typeof AuthAgentsRouteWithChildren
  '/_auth/dev-widgets': typeof AuthDevWidgetsRoute
  '/_auth/explore': typeof AuthExploreRoute
  '/_auth/files': typeof AuthFilesRoute
  '/_auth/folders': typeof AuthFoldersRoute
  '/_auth/help': typeof AuthHelpRoute
  '/_auth/knowledge': typeof AuthKnowledgeRouteWithChildren
  '/_auth/mcp': typeof AuthMcpRoute
  '/_auth/model-compare': typeof AuthModelCompareRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/playground': typeof AuthPlaygroundRoute
  '/_auth/prompts': typeof AuthPromptsRoute
  '/_auth/research': typeof AuthResearchRoute
  '/_auth/sandbox': typeof AuthSandboxRoute
  '/_auth/search': typeof AuthSearchRoute
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/_auth/tools': typeof AuthToolsRoute
  '/_auth/usage': typeof AuthUsageRoute
  '/shared/$token': typeof SharedTokenRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/admin/analytics': typeof AuthAdminAnalyticsRoute
  '/_auth/admin/audit': typeof AuthAdminAuditRoute
  '/_auth/admin/billing': typeof AuthAdminBillingRoute
  '/_auth/admin/branding': typeof AuthAdminBrandingRoute
  '/_auth/admin/content-filter': typeof AuthAdminContentFilterRoute
  '/_auth/admin/data-retention': typeof AuthAdminDataRetentionRoute
  '/_auth/admin/domains': typeof AuthAdminDomainsRoute
  '/_auth/admin/evals': typeof AuthAdminEvalsRoute
  '/_auth/admin/groups': typeof AuthAdminGroupsRoute
  '/_auth/admin/health': typeof AuthAdminHealthRoute
  '/_auth/admin/integrations': typeof AuthAdminIntegrationsRoute
  '/_auth/admin/members': typeof AuthAdminMembersRoute
  '/_auth/admin/models': typeof AuthAdminModelsRoute
  '/_auth/admin/org-settings': typeof AuthAdminOrgSettingsRoute
  '/_auth/admin/rate-limits': typeof AuthAdminRateLimitsRoute
  '/_auth/admin/security': typeof AuthAdminSecurityRoute
  '/_auth/admin/sso': typeof AuthAdminSsoRoute
  '/_auth/agents/$id': typeof AuthAgentsIdRoute
  '/_auth/agents/marketplace': typeof AuthAgentsMarketplaceRoute
  '/_auth/agents/new': typeof AuthAgentsNewRoute
  '/_auth/conversations/$id': typeof AuthConversationsIdRoute
  '/_auth/conversations/new': typeof AuthConversationsNewRoute
  '/_auth/knowledge/$id': typeof AuthKnowledgeIdRoute
  '/_auth/knowledge/new': typeof AuthKnowledgeNewRoute
  '/_auth/settings/api-keys': typeof AuthSettingsApiKeysRoute
  '/_auth/settings/appearance': typeof AuthSettingsAppearanceRoute
  '/_auth/settings/import-export': typeof AuthSettingsImportExportRoute
  '/_auth/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
  '/_auth/settings/security': typeof AuthSettingsSecurityRoute
  '/_auth/settings/shortcuts': typeof AuthSettingsShortcutsRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/agents'
    | '/dev-widgets'
    | '/explore'
    | '/files'
    | '/folders'
    | '/help'
    | '/knowledge'
    | '/mcp'
    | '/model-compare'
    | '/onboarding'
    | '/playground'
    | '/prompts'
    | '/research'
    | '/sandbox'
    | '/search'
    | '/settings'
    | '/tools'
    | '/usage'
    | '/shared/$token'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/branding'
    | '/admin/content-filter'
    | '/admin/data-retention'
    | '/admin/domains'
    | '/admin/evals'
    | '/admin/groups'
    | '/admin/health'
    | '/admin/integrations'
    | '/admin/members'
    | '/admin/models'
    | '/admin/org-settings'
    | '/admin/rate-limits'
    | '/admin/security'
    | '/admin/sso'
    | '/agents/$id'
    | '/agents/marketplace'
    | '/agents/new'
    | '/conversations/$id'
    | '/conversations/new'
    | '/knowledge/$id'
    | '/knowledge/new'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/import-export'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/shortcuts'
    | '/admin/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/agents'
    | '/dev-widgets'
    | '/explore'
    | '/files'
    | '/folders'
    | '/help'
    | '/knowledge'
    | '/mcp'
    | '/model-compare'
    | '/onboarding'
    | '/playground'
    | '/prompts'
    | '/research'
    | '/sandbox'
    | '/search'
    | '/tools'
    | '/usage'
    | '/shared/$token'
    | '/'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/branding'
    | '/admin/content-filter'
    | '/admin/data-retention'
    | '/admin/domains'
    | '/admin/evals'
    | '/admin/groups'
    | '/admin/health'
    | '/admin/integrations'
    | '/admin/members'
    | '/admin/models'
    | '/admin/org-settings'
    | '/admin/rate-limits'
    | '/admin/security'
    | '/admin/sso'
    | '/agents/$id'
    | '/agents/marketplace'
    | '/agents/new'
    | '/conversations/$id'
    | '/conversations/new'
    | '/knowledge/$id'
    | '/knowledge/new'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/import-export'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/shortcuts'
    | '/admin'
    | '/settings'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/signup'
    | '/_auth/admin'
    | '/_auth/agents'
    | '/_auth/dev-widgets'
    | '/_auth/explore'
    | '/_auth/files'
    | '/_auth/folders'
    | '/_auth/help'
    | '/_auth/knowledge'
    | '/_auth/mcp'
    | '/_auth/model-compare'
    | '/_auth/onboarding'
    | '/_auth/playground'
    | '/_auth/prompts'
    | '/_auth/research'
    | '/_auth/sandbox'
    | '/_auth/search'
    | '/_auth/settings'
    | '/_auth/tools'
    | '/_auth/usage'
    | '/shared/$token'
    | '/_auth/'
    | '/_auth/admin/analytics'
    | '/_auth/admin/audit'
    | '/_auth/admin/billing'
    | '/_auth/admin/branding'
    | '/_auth/admin/content-filter'
    | '/_auth/admin/data-retention'
    | '/_auth/admin/domains'
    | '/_auth/admin/evals'
    | '/_auth/admin/groups'
    | '/_auth/admin/health'
    | '/_auth/admin/integrations'
    | '/_auth/admin/members'
    | '/_auth/admin/models'
    | '/_auth/admin/org-settings'
    | '/_auth/admin/rate-limits'
    | '/_auth/admin/security'
    | '/_auth/admin/sso'
    | '/_auth/agents/$id'
    | '/_auth/agents/marketplace'
    | '/_auth/agents/new'
    | '/_auth/conversations/$id'
    | '/_auth/conversations/new'
    | '/_auth/knowledge/$id'
    | '/_auth/knowledge/new'
    | '/_auth/settings/api-keys'
    | '/_auth/settings/appearance'
    | '/_auth/settings/import-export'
    | '/_auth/settings/notifications'
    | '/_auth/settings/profile'
    | '/_auth/settings/security'
    | '/_auth/settings/shortcuts'
    | '/_auth/admin/'
    | '/_auth/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SharedTokenRoute: typeof SharedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/usage': {
      id: '/_auth/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthUsageRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tools': {
      id: '/_auth/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthToolsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search': {
      id: '/_auth/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthSearchRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sandbox': {
      id: '/_auth/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof AuthSandboxRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/research': {
      id: '/_auth/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthResearchRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/prompts': {
      id: '/_auth/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AuthPromptsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/playground': {
      id: '/_auth/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AuthPlaygroundRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/model-compare': {
      id: '/_auth/model-compare'
      path: '/model-compare'
      fullPath: '/model-compare'
      preLoaderRoute: typeof AuthModelCompareRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mcp': {
      id: '/_auth/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof AuthMcpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/knowledge': {
      id: '/_auth/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthKnowledgeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/help': {
      id: '/_auth/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthHelpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/folders': {
      id: '/_auth/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof AuthFoldersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/files': {
      id: '/_auth/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthFilesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/explore': {
      id: '/_auth/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthExploreRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dev-widgets': {
      id: '/_auth/dev-widgets'
      path: '/dev-widgets'
      fullPath: '/dev-widgets'
      preLoaderRoute: typeof AuthDevWidgetsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents': {
      id: '/_auth/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthAgentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/settings/shortcuts': {
      id: '/_auth/settings/shortcuts'
      path: '/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof AuthSettingsShortcutsRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/security': {
      id: '/_auth/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthSettingsSecurityRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/notifications': {
      id: '/_auth/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthSettingsNotificationsRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/import-export': {
      id: '/_auth/settings/import-export'
      path: '/import-export'
      fullPath: '/settings/import-export'
      preLoaderRoute: typeof AuthSettingsImportExportRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/appearance': {
      id: '/_auth/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthSettingsAppearanceRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/api-keys': {
      id: '/_auth/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthSettingsApiKeysRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/knowledge/new': {
      id: '/_auth/knowledge/new'
      path: '/new'
      fullPath: '/knowledge/new'
      preLoaderRoute: typeof AuthKnowledgeNewRouteImport
      parentRoute: typeof AuthKnowledgeRoute
    }
    '/_auth/knowledge/$id': {
      id: '/_auth/knowledge/$id'
      path: '/$id'
      fullPath: '/knowledge/$id'
      preLoaderRoute: typeof AuthKnowledgeIdRouteImport
      parentRoute: typeof AuthKnowledgeRoute
    }
    '/_auth/conversations/new': {
      id: '/_auth/conversations/new'
      path: '/conversations/new'
      fullPath: '/conversations/new'
      preLoaderRoute: typeof AuthConversationsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/conversations/$id': {
      id: '/_auth/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof AuthConversationsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/new': {
      id: '/_auth/agents/new'
      path: '/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthAgentsNewRouteImport
      parentRoute: typeof AuthAgentsRoute
    }
    '/_auth/agents/marketplace': {
      id: '/_auth/agents/marketplace'
      path: '/marketplace'
      fullPath: '/agents/marketplace'
      preLoaderRoute: typeof AuthAgentsMarketplaceRouteImport
      parentRoute: typeof AuthAgentsRoute
    }
    '/_auth/agents/$id': {
      id: '/_auth/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AuthAgentsIdRouteImport
      parentRoute: typeof AuthAgentsRoute
    }
    '/_auth/admin/sso': {
      id: '/_auth/admin/sso'
      path: '/sso'
      fullPath: '/admin/sso'
      preLoaderRoute: typeof AuthAdminSsoRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/security': {
      id: '/_auth/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthAdminSecurityRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/rate-limits': {
      id: '/_auth/admin/rate-limits'
      path: '/rate-limits'
      fullPath: '/admin/rate-limits'
      preLoaderRoute: typeof AuthAdminRateLimitsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/org-settings': {
      id: '/_auth/admin/org-settings'
      path: '/org-settings'
      fullPath: '/admin/org-settings'
      preLoaderRoute: typeof AuthAdminOrgSettingsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/models': {
      id: '/_auth/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AuthAdminModelsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/members': {
      id: '/_auth/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthAdminMembersRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/integrations': {
      id: '/_auth/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthAdminIntegrationsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/health': {
      id: '/_auth/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AuthAdminHealthRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/groups': {
      id: '/_auth/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AuthAdminGroupsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/evals': {
      id: '/_auth/admin/evals'
      path: '/evals'
      fullPath: '/admin/evals'
      preLoaderRoute: typeof AuthAdminEvalsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/domains': {
      id: '/_auth/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AuthAdminDomainsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/data-retention': {
      id: '/_auth/admin/data-retention'
      path: '/data-retention'
      fullPath: '/admin/data-retention'
      preLoaderRoute: typeof AuthAdminDataRetentionRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/content-filter': {
      id: '/_auth/admin/content-filter'
      path: '/content-filter'
      fullPath: '/admin/content-filter'
      preLoaderRoute: typeof AuthAdminContentFilterRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/branding': {
      id: '/_auth/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AuthAdminBrandingRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/billing': {
      id: '/_auth/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthAdminBillingRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/audit': {
      id: '/_auth/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthAdminAuditRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/analytics': {
      id: '/_auth/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthAdminAnalyticsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminAnalyticsRoute: typeof AuthAdminAnalyticsRoute
  AuthAdminAuditRoute: typeof AuthAdminAuditRoute
  AuthAdminBillingRoute: typeof AuthAdminBillingRoute
  AuthAdminBrandingRoute: typeof AuthAdminBrandingRoute
  AuthAdminContentFilterRoute: typeof AuthAdminContentFilterRoute
  AuthAdminDataRetentionRoute: typeof AuthAdminDataRetentionRoute
  AuthAdminDomainsRoute: typeof AuthAdminDomainsRoute
  AuthAdminEvalsRoute: typeof AuthAdminEvalsRoute
  AuthAdminGroupsRoute: typeof AuthAdminGroupsRoute
  AuthAdminHealthRoute: typeof AuthAdminHealthRoute
  AuthAdminIntegrationsRoute: typeof AuthAdminIntegrationsRoute
  AuthAdminMembersRoute: typeof AuthAdminMembersRoute
  AuthAdminModelsRoute: typeof AuthAdminModelsRoute
  AuthAdminOrgSettingsRoute: typeof AuthAdminOrgSettingsRoute
  AuthAdminRateLimitsRoute: typeof AuthAdminRateLimitsRoute
  AuthAdminSecurityRoute: typeof AuthAdminSecurityRoute
  AuthAdminSsoRoute: typeof AuthAdminSsoRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminAnalyticsRoute: AuthAdminAnalyticsRoute,
  AuthAdminAuditRoute: AuthAdminAuditRoute,
  AuthAdminBillingRoute: AuthAdminBillingRoute,
  AuthAdminBrandingRoute: AuthAdminBrandingRoute,
  AuthAdminContentFilterRoute: AuthAdminContentFilterRoute,
  AuthAdminDataRetentionRoute: AuthAdminDataRetentionRoute,
  AuthAdminDomainsRoute: AuthAdminDomainsRoute,
  AuthAdminEvalsRoute: AuthAdminEvalsRoute,
  AuthAdminGroupsRoute: AuthAdminGroupsRoute,
  AuthAdminHealthRoute: AuthAdminHealthRoute,
  AuthAdminIntegrationsRoute: AuthAdminIntegrationsRoute,
  AuthAdminMembersRoute: AuthAdminMembersRoute,
  AuthAdminModelsRoute: AuthAdminModelsRoute,
  AuthAdminOrgSettingsRoute: AuthAdminOrgSettingsRoute,
  AuthAdminRateLimitsRoute: AuthAdminRateLimitsRoute,
  AuthAdminSecurityRoute: AuthAdminSecurityRoute,
  AuthAdminSsoRoute: AuthAdminSsoRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthAgentsRouteChildren {
  AuthAgentsIdRoute: typeof AuthAgentsIdRoute
  AuthAgentsMarketplaceRoute: typeof AuthAgentsMarketplaceRoute
  AuthAgentsNewRoute: typeof AuthAgentsNewRoute
}

const AuthAgentsRouteChildren: AuthAgentsRouteChildren = {
  AuthAgentsIdRoute: AuthAgentsIdRoute,
  AuthAgentsMarketplaceRoute: AuthAgentsMarketplaceRoute,
  AuthAgentsNewRoute: AuthAgentsNewRoute,
}

const AuthAgentsRouteWithChildren = AuthAgentsRoute._addFileChildren(
  AuthAgentsRouteChildren,
)

interface AuthKnowledgeRouteChildren {
  AuthKnowledgeIdRoute: typeof AuthKnowledgeIdRoute
  AuthKnowledgeNewRoute: typeof AuthKnowledgeNewRoute
}

const AuthKnowledgeRouteChildren: AuthKnowledgeRouteChildren = {
  AuthKnowledgeIdRoute: AuthKnowledgeIdRoute,
  AuthKnowledgeNewRoute: AuthKnowledgeNewRoute,
}

const AuthKnowledgeRouteWithChildren = AuthKnowledgeRoute._addFileChildren(
  AuthKnowledgeRouteChildren,
)

interface AuthSettingsRouteChildren {
  AuthSettingsApiKeysRoute: typeof AuthSettingsApiKeysRoute
  AuthSettingsAppearanceRoute: typeof AuthSettingsAppearanceRoute
  AuthSettingsImportExportRoute: typeof AuthSettingsImportExportRoute
  AuthSettingsNotificationsRoute: typeof AuthSettingsNotificationsRoute
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
  AuthSettingsSecurityRoute: typeof AuthSettingsSecurityRoute
  AuthSettingsShortcutsRoute: typeof AuthSettingsShortcutsRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsApiKeysRoute: AuthSettingsApiKeysRoute,
  AuthSettingsAppearanceRoute: AuthSettingsAppearanceRoute,
  AuthSettingsImportExportRoute: AuthSettingsImportExportRoute,
  AuthSettingsNotificationsRoute: AuthSettingsNotificationsRoute,
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
  AuthSettingsSecurityRoute: AuthSettingsSecurityRoute,
  AuthSettingsShortcutsRoute: AuthSettingsShortcutsRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthAgentsRoute: typeof AuthAgentsRouteWithChildren
  AuthDevWidgetsRoute: typeof AuthDevWidgetsRoute
  AuthExploreRoute: typeof AuthExploreRoute
  AuthFilesRoute: typeof AuthFilesRoute
  AuthFoldersRoute: typeof AuthFoldersRoute
  AuthHelpRoute: typeof AuthHelpRoute
  AuthKnowledgeRoute: typeof AuthKnowledgeRouteWithChildren
  AuthMcpRoute: typeof AuthMcpRoute
  AuthModelCompareRoute: typeof AuthModelCompareRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthPlaygroundRoute: typeof AuthPlaygroundRoute
  AuthPromptsRoute: typeof AuthPromptsRoute
  AuthResearchRoute: typeof AuthResearchRoute
  AuthSandboxRoute: typeof AuthSandboxRoute
  AuthSearchRoute: typeof AuthSearchRoute
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthToolsRoute: typeof AuthToolsRoute
  AuthUsageRoute: typeof AuthUsageRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthConversationsIdRoute: typeof AuthConversationsIdRoute
  AuthConversationsNewRoute: typeof AuthConversationsNewRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthAgentsRoute: AuthAgentsRouteWithChildren,
  AuthDevWidgetsRoute: AuthDevWidgetsRoute,
  AuthExploreRoute: AuthExploreRoute,
  AuthFilesRoute: AuthFilesRoute,
  AuthFoldersRoute: AuthFoldersRoute,
  AuthHelpRoute: AuthHelpRoute,
  AuthKnowledgeRoute: AuthKnowledgeRouteWithChildren,
  AuthMcpRoute: AuthMcpRoute,
  AuthModelCompareRoute: AuthModelCompareRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthPlaygroundRoute: AuthPlaygroundRoute,
  AuthPromptsRoute: AuthPromptsRoute,
  AuthResearchRoute: AuthResearchRoute,
  AuthSandboxRoute: AuthSandboxRoute,
  AuthSearchRoute: AuthSearchRoute,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthToolsRoute: AuthToolsRoute,
  AuthUsageRoute: AuthUsageRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthConversationsIdRoute: AuthConversationsIdRoute,
  AuthConversationsNewRoute: AuthConversationsNewRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SharedTokenRoute: SharedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
